# Generated by Django 4.2.1 on 2023-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphicDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Category", models.CharField(max_length=100)),
                ("UploadDate", models.DateTimeField(auto_now_add=True)),
                ("updateDate", models.DateTimeField(auto_now=True)),
                ("is_feature", models.BooleanField(default=False)),
                ("Image", models.ImageField(upload_to="Image/Graphic Designs")),
            ],
        ),
    ]
