# Generated by Django 4.2.1 on 2023-05-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphicDesigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicdesign",
            name="Category",
            field=models.CharField(
                choices=[
                    ("Social Media Design", "Social Media Design"),
                    ("Face Book Covers", "Face Book Covers"),
                    ("Flyer Design", "Flyer Design"),
                    ("Business Card Design", "Business Card Design"),
                ],
                default="Social Media Design",
                max_length=100,
            ),
        ),
    ]
