# Generated by Django 4.2.5 on 2023-09-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphicDesign',
            new_name='Graphic_Designs',
        ),
    ]
