# Generated by Django 4.2.1 on 2023-05-10 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphicDesigns", "0002_alter_graphicdesign_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicdesign",
            name="UploadDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 10, 16, 51, 31, 32229)
            ),
        ),
        migrations.AlterField(
            model_name="graphicdesign",
            name="updateDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 10, 16, 51, 31, 32229)
            ),
        ),
    ]
