# Generated by Django 4.2.5 on 2023-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesigns', '0003_alter_graphic_designs_design_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic_designs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
