# Generated by Django 4.2.1 on 2023-05-10 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphicDesigns", "0004_alter_graphicdesign_uploaddate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="graphicdesign", name="updateDate",),
        migrations.AlterField(
            model_name="graphicdesign",
            name="UploadDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 10, 22, 0, 42, 627086)
            ),
        ),
    ]
