# Generated by Django 4.2.1 on 2023-05-11 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphicDesigns", "0005_remove_graphicdesign_updatedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicdesign",
            name="UploadDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 11, 17, 13, 4, 17311)
            ),
        ),
    ]
