# Generated by Django 4.2.1 on 2023-05-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GraphicDesigns", "0009_alter_graphicdesign_uploaddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicdesign",
            name="UploadDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 11, 19, 53, 29, 536761)
            ),
        ),
    ]
