# Generated by Django 4.2.1 on 2023-05-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webportfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Category", models.CharField(max_length=100)),
                ("Url", models.URLField(max_length=250)),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 11, 17, 19, 24, 613968)
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                ("Image", models.ImageField(upload_to="Image/WebDesigns")),
            ],
        ),
    ]
