# Generated by Django 4.2.1 on 2023-05-11 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebPortfolios", "0002_alter_webportfolio_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webportfolio",
            name="upload_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 11, 19, 56, 1, 414531)
            ),
        ),
    ]
