# Generated by Django 4.2.5 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webdesigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=300)),
                ('url', models.SlugField(max_length=600)),
                ('is_feature', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Images/Website Design')),
            ],
            options={
                'verbose_name': 'Website Design',
                'verbose_name_plural': 'Website Designs',
            },
        ),
    ]
