# Generated by Django 4.2.5 on 2023-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdesigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesigns',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
