# Generated by Django 4.2.5 on 2023-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdesigns', '0002_alter_webdesigns_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesigns',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
