# Generated by Django 4.2.1 on 2023-05-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=100)),
                ("Last_name", models.CharField(max_length=100)),
                ("Email_id", models.EmailField(max_length=200)),
                ("Contact_no", models.CharField(max_length=100)),
                (
                    "Service_type",
                    models.CharField(
                        choices=[
                            ("Website", "Website"),
                            ("Graphic Design", "Graphic Design"),
                        ],
                        default="Website",
                    ),
                ),
                (
                    "Order_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 11, 19, 53, 29, 546762)
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Delivered", "Delivered"),
                            ("Revision", "Revision"),
                            ("Completed", "Completed"),
                        ],
                        max_length=100,
                    ),
                ),
                ("order_detail", models.TextField()),
            ],
        ),
    ]
