# Generated by Django 4.2.1 on 2023-05-11 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="Order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 11, 19, 56, 1, 416530)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Delivered", "Delivered"),
                    ("Revision", "Revision"),
                    ("Completed", "Completed"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
