# Generated by Django 4.2.5 on 2023-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered'), ('In Revision', 'In Revision'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Active', max_length=300),
        ),
    ]
